name: Deploy to WP Engine (Development)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy theme to WP Engine Dev
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_ENV: valtasdev
          REMOTE_PATH: "wp-content/themes/valtas-theme/"
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
